### ISSUE TITLE
Update to 9-2019q4-major

### ISSUE THREAD

**Issue by carlescufi** [n3rd4i/gcc-arm-embedded#1]
Available here:
https://developer.arm.com/tools-and-software/open-source-software/developer-tools/gnu-toolchain/gnu-rm/downloads

**Comment by n3rd4i** [comment]
I've updated the package with latest version, pending review.
Until then could be force installed with:
* `choco install gcc-arm-embedded --version 9.2.1`

Upgrade with:
* `choco upgrade gcc-arm-embedded --version 9.2.1`

**Comment by carlescufi** [comment]
Thank you @n3rd4i, this is most welcome.

**Comment by aeremin** [comment]
Thanks! I think it was approved today.

**Comment by n3rd4i** [comment]
It has been approved so I can close this ticket
